# Dockerfile.clients

# --- ETAPA 1: BUILD ---
FROM node:20-alpine AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build clients

# --- ETAPA 2: PRODUCTION ---
FROM node:20-alpine AS production
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/package*.json ./
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist/apps/clients ./dist
CMD ["node", "dist/main.js"]